[package]
name = "chopin-kernel"
version = "0.1.0"
edition = "2021"

authors = [
  "Samir Bioud <samir@induct.ie>"
]

description = "The Chopin Kernel"

[dependencies]


chopin-kernel-stage0 = { path = "./stage0/" }
sbi = "0.2.0"
