[build]
target = "riscv64imac-unknown-none-elf"



[target.riscv64imac-unknown-none-elf]
linker = "riscv64-linux-gnu-ld"
runner = """
qemu-system-riscv64 \
    -machine sifive_u,firmware=/usr/share/opensbi/lp64/generic/firmware/fw_dynamic.bin \
    -cpu rv64 \
    -smp 4 \
    -m 128M \
    -nographic \
    -kernel 
"""
